name: Schedule
on:
#  schedule:
#    - cron: "0 0-14 * * *"
  workflow_dispatch:
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          echo "Calling API"
          curl -X POST ${{ secrets.API_URL }}/cron
